using FileManager.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FileManager.Infrastructure.Data.Configurations;

/// <summary>
/// Entity configuration for FileMetadata.
/// </summary>
internal sealed class FileMetadataConfiguration : IEntityTypeConfiguration<FileMetadata>
{
    public void Configure(EntityTypeBuilder<FileMetadata> builder)
    {
        builder.ToTable("FileMetadata");

        // Primary Key
        builder.HasKey(f => f.Id);

        builder.Property(f => f.Id)
            .ValueGeneratedNever(); // Guid generated by domain

        // Properties
        builder.Property(f => f.FileName)
            .IsRequired()
            .HasMaxLength(255);

        builder.Property(f => f.Path)
            .IsRequired()
            .HasMaxLength(500);

        builder.Property(f => f.Size)
            .IsRequired();

        builder.Property(f => f.ContentType)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(f => f.Status)
            .IsRequired()
            .HasConversion<string>() // Store enum as string for readability
            .HasMaxLength(50);

        builder.Property(f => f.Hash)
            .HasMaxLength(128); // SHA-512 hash length

        builder.Property(f => f.Provider)
            .IsRequired()
            .HasConversion<string>() // Store enum as string
            .HasMaxLength(50);

        builder.Property(f => f.StorageKey)
            .IsRequired()
            .HasMaxLength(1000);

        builder.Property(f => f.UploadedAt)
            .IsRequired();

        builder.Property(f => f.ValidatedAt);

        builder.Property(f => f.ScannedAt);

        builder.Property(f => f.RejectionReason)
            .HasMaxLength(1000);

        // Indexes for common queries
        builder.HasIndex(f => f.StorageKey)
            .IsUnique()
            .HasDatabaseName("IX_FileMetadata_StorageKey");

        builder.HasIndex(f => f.Hash)
            .HasDatabaseName("IX_FileMetadata_Hash");

        builder.HasIndex(f => f.Status)
            .HasDatabaseName("IX_FileMetadata_Status");

        builder.HasIndex(f => f.Provider)
            .HasDatabaseName("IX_FileMetadata_Provider");

        builder.HasIndex(f => f.UploadedAt)
            .HasDatabaseName("IX_FileMetadata_UploadedAt");

        builder.HasIndex(f => new { f.Status, f.UploadedAt })
            .HasDatabaseName("IX_FileMetadata_Status_UploadedAt");

        // Ignore domain events (not persisted to database)
        builder.Ignore(f => f.DomainEvents);
    }
}
